--Caio Ribeiro -- RM99759 -- 1TDSPY
--Eduardo Jablinski -- RM550975 -- 1TDSPY
--Gabriel Cunha -- RM98074 -- 1TDSPX
--Guilherme Riofrio -- RM550137 -- 1TDSPY
--Natalia Scigliano -- RM98430 -- 1TDSPX

--Aqui todas as tabelas estão sendo deletadas para não dar conflito com outros trabalhos;
--Todas as tabelas e tudo relacionado à elas estão sendo deletados primeiramente.
DROP TABLE TB_ACS_VEICULO CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_MODELO CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_USER CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_MODELOAPOLICE CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_APOLICE CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_VEICULO_APOLICE CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_PRESTADOR CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_ORDEMSERVICO CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_MODAL CASCADE CONSTRAINTS;
DROP TABLE TB_ACS_MODAL_PRESTADOR CASCADE CONSTRAINTS;

--Criando uma tabela com os dados do veículo e adicionando uma PK:
CREATE TABLE TB_ACS_VEICULO
    (
        ID_VEICULO INT NOT NULL,
        ANO_VEICULO INT,
        PESO_VEICULO FLOAT,
        TIPO_COMBUSTIVEL VARCHAR2(40),
        COR_VEICULO VARCHAR2(30)
    );
ALTER TABLE TB_ACS_VEICULO ADD CONSTRAINT TB_ACS_VEICULO_PK PRIMARY KEY (ID_VEICULO);

--Criando uma tabela com os dados do modelo do veículo e adicionando uma PK e uma FK:
CREATE TABLE TB_ACS_MODELO
    (
        ID_MODELO INT NOT NULL,
        ID_VEICULO INT NOT NULL,
        ALTURA_MODELO FLOAT,
        LARGURA_MODELO FLOAT,
        COMPRIMENTO_MODELO FLOAT,
        CATEGORIA_MODELO VARCHAR2(50),
        MONTADORA_MODELO VARCHAR2(30)
    );
ALTER TABLE TB_ACS_MODELO ADD CONSTRAINT TB_ACS_MODELO_PK PRIMARY KEY (ID_MODELO);
ALTER TABLE TB_ACS_MODELO 
    ADD CONSTRAINT TB_ACS_MODELO_ID_VEICULO_FK FOREIGN KEY (ID_VEICULO)
        REFERENCES TB_ACS_VEICULO(ID_VEICULO);

--Criando uma tabela com informações do usuário e adicionando uma PK:
CREATE TABLE TB_ACS_USER(
    ID_USER INT NOT NULL,
    NOME_USER VARCHAR2(80) NOT NULL,
    CPF_USER VARCHAR2(11) NOT NULL,
    ENDERECO_USER VARCHAR2(80) NOT NULL,
    EMAIL_USER VARCHAR2(50) NOT NULL,
    TELEFONE_USER VARCHAR2(15) NOT NULL
);
ALTER TABLE TB_ACS_USER ADD CONSTRAINT TB_ACS_USER_ID_USER PRIMARY KEY (ID_USER);

--Criando uma tabela com informações da apólice e adicionando uma PK:
CREATE TABLE TB_ACS_MODELOAPOLICE(
    ID_MODELOAPOLICE INT NOT NULL,
    TIPO_COBERTURA VARCHAR2(80),
    PERIODO_VIGENCIA DATE,
    EXCLUSOES_APOLICE VARCHAR2(100)
);
ALTER TABLE TB_ACS_MODELOAPOLICE ADD CONSTRAINT TB_ACS_MODELOAPOLICE_ID_MODELOAPOLICE PRIMARY KEY (ID_MODELOAPOLICE);

--Criando uma tabela para interligar o usuário com a apólice, contendo informações da cobertura do plano. Adicionando uma PK e uma FK:
CREATE TABLE TB_ACS_APOLICE(
    ID_APOLICE INT NOT NULL,
    ID_MODELOAPOLICE INT NOT NULL,
    ID_USER INT NOT NULL,
    NUMERO_APOLICE VARCHAR2(40) NOT NULL
);
ALTER TABLE TB_ACS_APOLICE ADD CONSTRAINT TB_ACS_APOLICE_ID_APOLICE PRIMARY KEY (ID_APOLICE);
ALTER TABLE TB_ACS_APOLICE
    ADD CONSTRAINT TB_ACS_APOLICE_ID_MODELOAPOLICE_FK FOREIGN KEY(ID_MODELOAPOLICE)
        REFERENCES TB_ACS_MODELOAPOLICE(ID_MODELOAPOLICE);
        
--Criando uma tabela para interligar dados do veículo com a apolice, contendo também informações sobre a condição do veículo (se tiveram alterações por exemplo);
--Contém duas FK
CREATE TABLE TB_ACS_VEICULO_APOLICE(
    ID_VEICULO INT NOT NULL,
    ID_APOLICE INT NOT NULL,
    PLACA_VEICULO VARCHAR2(7) NOT NULL,
    CONDICAO_VEICULO VARCHAR2(100)
);
ALTER TABLE TB_ACS_VEICULO_APOLICE
    ADD CONSTRAINT TB_ACS_VEICULO_APOLICE_ID_VEICULO_FK FOREIGN KEY(ID_VEICULO)
        REFERENCES TB_ACS_VEICULO(ID_VEICULO);
        
ALTER TABLE TB_ACS_VEICULO_APOLICE
    ADD CONSTRAINT TB_ACS_VEICULO_APOLICE_ID_APOLICE_FK FOREIGN KEY(ID_APOLICE)
        REFERENCES TB_ACS_APOLICE(ID_APOLICE);

--Criando a tabela com informações do prestador de serviços da Porto Seguro, com uma PK:
CREATE TABLE TB_ACS_PRESTADOR(
    ID_PRESTADOR INT NOT NULL,
    NOME_PRESTADOR VARCHAR2(50) NOT NULL,
    TELEFONE_PRESTADOR VARCHAR2(15) NOT NULL,
    ULTIMA_LOCALIZAO_PRESTADOR VARCHAR2(30)
);
ALTER TABLE TB_ACS_PRESTADOR ADD CONSTRAINT TB_ACS_PRESTADOR_ID_PRESTADOR_PK PRIMARY KEY(ID_PRESTADOR);

--Criando uma tabela com a ordem de serviço;
--Ela conterá uma PK e trará três FK, unindo informações do usuário, da apólice, do prestador de serviço e informações da abertura do chamado
CREATE TABLE TB_ACS_ORDEMSERVICO(
    ID_ORDEMSERVICO INT NOT NULL,
    ID_APOLICE INT NOT NULL,
    ID_PRESTADOR INT NOT NULL,
    ID_USER INT NOT NULL,
    DESCRICAO_ORDEMSERVICO VARCHAR2(100),
    DATAABERTURA_ORDEMSERVICO TIMESTAMP,
    DATAFECHAMENTO_ORDEMSERVICO TIMESTAMP,
    STATUS_ORDEMSERVICO VARCHAR2(50),
    LOCALIZACAO_ORDEMSERVICO VARCHAR2(100)
);
ALTER TABLE TB_ACS_ORDEMSERVICO ADD CONSTRAINT TB_ACS_ORDEMSERVICO_ID_ORDEMSERVICO_PK PRIMARY KEY(ID_ORDEMSERVICO);

ALTER TABLE TB_ACS_ORDEMSERVICO
    ADD CONSTRAINT TB_ACS_ORDEMSERVICO_ID_APOLICE_FK FOREIGN KEY(ID_APOLICE)
        REFERENCES TB_ACS_APOLICE(ID_APOLICE);

ALTER TABLE TB_ACS_ORDEMSERVICO
    ADD CONSTRAINT TB_ACS_ORDEMSERVICO_ID_PRESTADOR_FK FOREIGN KEY(ID_PRESTADOR)
        REFERENCES TB_ACS_PRESTADOR(ID_PRESTADOR);

ALTER TABLE TB_ACS_ORDEMSERVICO
    ADD CONSTRAINT TB_ACS_ORDEMSERVICO_ID_USER_FK FOREIGN KEY(ID_USER)
        REFERENCES TB_ACS_USER(ID_USER);

--Criando uma tabela para o tipo de guincho, com uma PK e informações do Guincho
CREATE TABLE TB_ACS_MODAL(
    ID_MODAL INT NOT NULL,
    TIPO_MODAL VARCHAR2(80),
    CAPACIDADE_MODAL VARCHAR2(30),
    CAPACIDADE_DE_INTERMODALIDADE VARCHAR2(80)
);
ALTER TABLE TB_ACS_MODAL ADD CONSTRAINT TB_ACS_MODAL_ID_MODAL_PK PRIMARY KEY(ID_MODAL);

--Criando uma tabela para interligar informações do prestador de serviço e do modal de atendimento, bem como a placa do veículo guincho;
--Ela contém duas FKs
CREATE TABLE TB_ACS_MODAL_PRESTADOR(
    ID_PRESTADOR INT NOT NULL,
    ID_MODAL INT NOT NULL,
    PLACA_MODAL_PRESTADOR VARCHAR2(7)
);
ALTER TABLE TB_ACS_MODAL_PRESTADOR 
    ADD CONSTRAINT TB_ACS_MODAL_PRESTADOR_ID_PRESTADOR_FK FOREIGN KEY(ID_PRESTADOR)
        REFERENCES TB_ACS_PRESTADOR(ID_PRESTADOR);
ALTER TABLE TB_ACS_MODAL_PRESTADOR
    ADD CONSTRAINT TB_ACS_MODAL_PRESTADOR_ID_MODAL_FK FOREIGN KEY(ID_MODAL)
        REFERENCES TB_ACS_MODAL(ID_MODAL);

--Comando Select para mostrar todas as tabelas que foram criadas anteriormente.
SELECT * FROM ALL_TABLES;